name: Tag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to set'
        required: true
        type: string

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          git config --global user.email "<>"
          git config --global user.name "Bot"
          tag=v${{ inputs.tag }}
          git tag -a $tag -m "Setting a nice tag"
          git push origin $tag
