name: Test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "$( yq '.global' .github/workflows/env.yml | sed 's/: /=/' )" >> $GITHUB_ENV
      - run: echo $a
