name: Test
on:
  workflow_dispatch:
    inputs:
      value:
        type: text
        required: false
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          value=${{ inputs.value == "a" ? "Value set" | "Value NOT set" }}
          echo "value: $value"
