name: TagTest

on:
  create:
    branches:
      - 'release/**'
  push:
    branches:
      - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ref_name: ${{ github.ref_name }}"
