name: TagTest

on:
  create:
    tags:
      - '*'
  push:
    tags:
      - '*'
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ref_name: ${{ github.ref_name }}"
