name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ref_name: ${{ github.ref_name }}"
          echo "head_ref: ${{ github.head_ref }}"
          echo "PR #: ${{ github.event.number }}"
